Fix tab margins behavior on FFG page
unicorn-utterances/unicorn-utterances pull request #480
Opened 2023-02-08 02:52 UTC by fennifith

Fixes a styling issue on the FFG page that caused the static tab heights implementation (#449) to break.

2023-02-12 06:48 UTC, crutchcorn requested changes
This removes the "focus on center of tabs" when the tabs list is not small.

This functionality is important because otherwise, like in my book, the changing of tabs drastically impacts the scroll height and such

2023-03-12 15:58 UTC, fennifith commented
Leaving a note for future reference - this is waiting on testing for iOS/Safari to ensure that there are no scroll jumps when tabs are selected. Latest Chrome and Firefox versions have not been able to reproduce any scroll jumps.

Link for testing: https://unicorn-utterances-git-fix-tab-margins-on-ffg-oceanbit.vercel.app/posts/angular-extend-class

2023-03-16 13:20 UTC, crutchcorn approved these changes

2023-03-16 22:16 UTC, fennifith commented
Agree that users could see the extra margin as a bug - I think this would appear more intentional if the margin was inside the tab container, but IIRC we decided against that for other reasons.

Merging for now, and we can revisit the design aspects later if needed.

2023-03-16 22:16 UTC, merged